---
#
# Install and enable the browser exploit server as a systemd service
#
- name: "Install systemd service file"
  copy:
    src: "../../../../Attacker/{{ service_name }}.service"
    dest: /etc/systemd/system/{{ service_name }}.service
    owner: root
    group: root
    mode: '0664'

- name: "Enable the {{ service_name }} service to run at startup"
  systemd:
    name: "{{ service_name }}"
    daemon_reload: yes
    enabled: yes
    state: started
