---

# This contains a dll file which is a dependency for python
# It solves the error:
# "The program can't start because api-ms-win-crt-runtime-l1-1-0.dll is missing"
- name: Install Visual C++ redistributable
  win_chocolatey:
    name: vcredist2015
    state: present
    architecture: x86
    state: latest

- name: Install Python 3.7.3
  win_chocolatey:
    name: python3
    state: present
    architecture: x86
    version: 3.7.3
    force: yes # forces reinstall, thereby fixing any errors
    pinned: yes
