---
# Ansible playbook for the Windows 7 client
# Run the playbook using ` ansible-playbook client_playbook.yml -i hosts `

- hosts: client
  gather_facts: true
  
  vars:
   
  roles:
    - win_setup_user
    - win_kb3033929
    - win_disable_uac
    - win_disable_firewall
    - winlogbeat
    - win_nettime
    - win_adobe_reader
    - win_firefox
    - win_thunderbird
    - win_flashplayer
    - win_python
    - win_assets
