---
#
# Replace the sqlmap wordlist with a custom one
#
- name: "Copy the re-encoded wordlist zip file"
  copy:
    src: "../../../../Attacker/sqlmap/wordlist.re-encoded_to_utf-8.zip"
    dest: "{{ sqlmap_wl_location }}{{ sqlmap_wl_zip_name }}"
  
- name: "Extract re-encoded wordlist into {{ sqlmap_wl_location }}"
  unarchive:
    src: "{{ sqlmap_wl_location }}{{ sqlmap_wl_zip_name }}"
    dest: "{{ sqlmap_wl_location }}"
    remote_src: yes
