---
# Disable the windows firewall using registries

- name: Disable windows firewall for all network profiles
  win_regedit:
    path: "{{ item }}"
    name: "EnableFirewall"
    value: 0
    type: dword
  loop:
    - 'HKLM:\SYSTEM\CurrentControlSet\Services\SharedAccess\Parameters\FirewallPolicy\DomainProfile'
    - 'HKLM:\SYSTEM\CurrentControlSet\Services\SharedAccess\Parameters\FirewallPolicy\PublicProfile'
    - 'HKLM:\SYSTEM\CurrentControlSet\Services\SharedAccess\Parameters\FirewallPolicy\StandardProfile'
