---
- name: Create Users "setup" and "ssh"
  win_user:
    name: "{{ item }}"
    password: breach
    state: present
    password_never_expires: yes
    groups:
      - Administrators
  loop:
    - setup
    - ssh
    
- name: Set default Username for autologon
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
    name: DefaultUserName
    data: setup

- name: Set default password for autologon
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
    name: DefaultPassword
    data: breach

- name: Set automatic logon (for the setup user)
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
    name: AutoAdminLogon
    data: 1
    type: dword
