---
- name: Ensure user setup is present
  win_user:
    name: setup
    password: breach
    state: present
    groups:
      - Administrators

# First setup logs on automatically,
# Then init_tbf_client.py changes the autologon to
# the specific user (client1, client2, etc.)

- name: Set default domain name for autologon
  win_regedit:
    path: HKLM:\Software\Microsoft\Windows NT\CurrentVersion\Winlogon
    name: DefaultDomainName
    data: BREACH
    
- name: Set default Username for autologon
  win_regedit:
    path: HKLM:\Software\Microsoft\Windows NT\CurrentVersion\Winlogon
    name: DefaultUserName
    data: setup

- name: Set default password for autologon
  win_regedit:
    path: HKLM:\Software\Microsoft\Windows NT\CurrentVersion\Winlogon
    name: DefaultPassword
    data: breach

- name: Set automatic logon (for the setup user)
  win_regedit:
    path: HKLM:\Software\Microsoft\Windows NT\CurrentVersion\Winlogon
    name: AutoAdminLogon
    data: 1
    type: dword
