---
# Refer: https://git.cs.uni-bonn.de/uetz/breach-framework/wikis/Time-Synchronization    

- name: Install nettime
  win_chocolatey:
    name: nettime
    state: present
    architecture: x86

- name: "Update registry path NetTime with entry 'hostname', and containing {{ ntp_server }}"
  win_regedit:
    path: "{{ nettime_reg_path }}"
    name: Hostname
    data: "{{ ntp_server }}"
    type: string

- name: Remove existing Hostname1,2,3 entries
  win_regedit:
    path: "{{ nettime_reg_path }}"
    name: "{{ item }}"
    state: absent
  loop:
    - Hostname1
    - Hostname2
    - Hostname3

- name: Set update interval to 5 minutes
  win_regedit:
    path: "{{ nettime_reg_path }}"
    name: SyncFreq
    data: 0x5
    type: dword
    
- name: Set update interval units to minutes
  win_regedit:
    path: "{{ nettime_reg_path }}"
    name: SyncFreqUnits
    data: 0x2 # indicates minutes
    type: dword
    
- name: Demote servers after 10 failures
  win_regedit:
    path: "{{ nettime_reg_path }}"
    name: DemoteOnErrorCount
    data: 0xa
    type: dword

- name: Switch off automatic update checks
  win_regedit:
    path: "{{ nettime_reg_path }}"
    name: AutomaticUpdateChecks
    data: 0x0
    type: dword

- name: Set max free run to 10 minutes
  win_regedit:
    path: "{{ nettime_reg_path }}"
    name: LostSync
    data: 0xa
    type: dword

- name: Set max free run units to minutes
  win_regedit:
    path: "{{ nettime_reg_path }}"
    name: LostSyncUnits
    data: 0x2
    type: dword
